DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tilaukset CASCADE;
DROP TABLE IF EXISTS Ateria CASCADE;
DROP TABLE IF EXISTS AterianValmistaja CASCADE;
DROP TABLE IF EXISTS TavaranValmistaja CASCADE;
DROP TABLE IF EXISTS Tavara CASCADE;