DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tilaus CASCADE;
DROP TABLE IF EXISTS Ateria CASCADE;
DROP TABLE IF EXISTS TavaranValmistaja CASCADE;
DROP TABLE IF EXISTS Tavara CASCADE;
DROP TABLE IF EXISTS Tilaustiedot CASCADE;
DROP TABLE IF EXISTS Lento CASCADE;